# Generated by Django 6.0 on 2026-01-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="topics.topic",
            ),
        ),
    ]
