# Generated by Django 6.0 on 2025-12-16 13:09

from django.db import migrations

from users.models import UserManager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", UserManager()),
            ],
        ),
    ]
