# Generated by Django 5.2.10 on 2026-01-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(default="ru", max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Europe/Moscow", max_length=50),
        ),
    ]
